name: pointnet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch>=1.7.0
  - numpy
  - tqdm
  - mkl
  - mkl-service
  - intel-openmp
  - pip
  - pip:
    - plyfile
